#!/bin/sh
cp Libc-498/include/_locale.h include/_locale.h
cp Libc-498/include/_structs.h include/_structs.h
cp Libc-498/include/_types.h include/_types.h
cp Libc-498/include/_wctype.h include/_wctype.h
cp Libc-498/include/alloca.h include/alloca.h
cp Libm-292.4/Source/PowerPC/math.h include/architecture/ppc/math.h
cp Libc-498/include/assert.h include/assert.h
# available.h	is missing
cp xnu-1228/bsd/bsm/audit.h include/bsm/audit.h.orig
cp Libc-498/include/ctype.h include/ctype.h.orig
cp Libc-498/include/dirent.h include/dirent.h.orig
cp Libc-498/include/errno.h include/errno.h
cp Libc-498/include/fcntl.h include/fcntl.h
cp Libc-498/include/limits.h include/limits.h
cp Libc-498/include/locale.h include/locale.h
cp xnu-1228/osfmk/mach/boolean.h include/mach/boolean.h
cp xnu-1228/osfmk/mach/machine/boolean.h include/mach/machine/boolean.h
cp xnu-1228/osfmk/mach/ppc/_structs.h include/mach/ppc/_structs.h
cp xnu-1228/osfmk/mach/ppc/boolean.h include/mach/ppc/boolean.h
cp xnu-1228/bsd/machine/_param.h include/machine/_param.h
cp xnu-1228/bsd/machine/_structs.h include/machine/_structs.h
cp xnu-1228/bsd/machine/_types.h include/machine/_types.h
cp xnu-1228/bsd/machine/endian.h include/machine/endian.h
cp Libc-498/include/machine/limits.h include/machine/limits.h
cp xnu-1228/bsd/machine/param.h include/machine/param.h
cp xnu-1228/bsd/machine/signal.h include/machine/signal.h
cp xnu-1228/bsd/machine/types.h include/machine/types.h
cp Libm-292.4/Source/math.h include/math.h
cp Libc-498/include/poll.h include/poll.h
cp xnu-1456.1.26/bsd/ppc/_limits.h include/ppc/_limits.h
cp xnu-1228/bsd/ppc/_param.h include/ppc/_param.h
cp xnu-1228/bsd/ppc/_structs.h include/ppc/_structs.h
cp xnu-1228/bsd/ppc/_types.h include/ppc/_types.h
cp xnu-1228/bsd/ppc/endian.h include/ppc/endian.h
cp xnu-1456.1.26/bsd/ppc/limits.h include/ppc/limits.h
cp xnu-1228/bsd/ppc/param.h include/ppc/param.h
cp xnu-1228/bsd/ppc/signal.h include/ppc/signal.h
cp xnu-1228/bsd/ppc/types.h include/ppc/types.h
cp Libc-498/pthreads/pthread.h include/pthread.h.orig
cp Libc-498/pthreads/pthread_impl.h include/pthread_impl.h
cp Libc-498/include/runetype.h include/runetype.h
cp Libc-498/pthreads/sched.h include/sched.h
cp Libc-498/include/stdio.h include/stdio.h.orig
cp Libc-498/include/stdlib.h include/stdlib.h.orig
cp Libc-498/include/string.h include/string.h.orig
cp xnu-1228/bsd/sys/_endian.h include/sys/_endian.h
cp xnu-1228/bsd/sys/_select.h include/sys/_select.h
cp xnu-1228/bsd/sys/_structs.h include/sys/_structs.h.orig
cp xnu-1228/bsd/sys/_types.h include/sys/_types.h.orig
cp xnu-1228/bsd/sys/appleapiopts.h include/sys/appleapiopts.h
cp xnu-1228/bsd/sys/cdefs.h include/sys/cdefs.h.orig
cp xnu-1228/bsd/sys/dirent.h include/sys/dirent.h.orig
cp xnu-1228/bsd/sys/errno.h include/sys/errno.h.orig
cp xnu-1228/bsd/sys/event.h include/sys/event.h.orig
cp xnu-1228/bsd/sys/fcntl.h include/sys/fcntl.h.orig
cp xnu-1228/bsd/sys/filio.h include/sys/filio.h
cp xnu-1228/bsd/sys/ioccom.h include/sys/ioccom.h
cp xnu-1228/bsd/sys/ioctl.h include/sys/ioctl.h.orig
cp xnu-1228/bsd/sys/lock.h include/sys/lock.h.orig
cp xnu-1228/bsd/sys/param.h include/sys/param.h.orig
cp xnu-1228/bsd/sys/poll.h include/sys/poll.h.orig
cp xnu-1228/bsd/sys/proc.h include/sys/proc.h.orig
cp xnu-1228/bsd/sys/queue.h include/sys/queue.h
cp xnu-1228/bsd/sys/resource.h include/sys/resource.h.orig
cp xnu-1228/bsd/sys/select.h include/sys/select.h.orig
cp xnu-1228/bsd/sys/signal.h include/sys/signal.h.orig
cp xnu-1228/bsd/sys/socket.h include/sys/socket.h.orig
cp xnu-1228/bsd/sys/sockio.h include/sys/sockio.h.orig
cp xnu-1228/bsd/sys/stat.h include/sys/stat.h.orig
cp Libc-498/include/sys/statvfs.h include/sys/statvfs.h
cp xnu-1228/bsd/sys/sysctl.h include/sys/sysctl.h.orig
cp xnu-1228/bsd/sys/syslimits.h include/sys/syslimits.h
cp xnu-1456.1.26/bsd/sys/time.h include/sys/time.h.orig
cp xnu-1228/bsd/sys/ttycom.h include/sys/ttycom.h.orig
cp xnu-1228/bsd/sys/types.h include/sys/types.h
cp xnu-1228/bsd/sys/ucred.h include/sys/ucred.h.orig
cp xnu-1228/bsd/sys/uio.h include/sys/uio.h.orig
cp xnu-1228/bsd/sys/unistd.h include/sys/unistd.h
cp xnu-1228/bsd/sys/vm.h include/sys/vm.h.orig
cp xnu-1228/bsd/sys/wait.h include/sys/wait.h.orig
cp Libc-498/include/time.h include/time.h.orig
cp Libc-498/include/unistd.h include/unistd.h.orig
cp Libc-498/include/utime.h include/utime.h
cp Libc-498/include/wchar.h include/wchar.h.orig
cp Libc-498/include/wctype.h include/wctype.h
